name: ClansPvP
main: me.jason.clanspvp.ClansPvP
version: 1.0.0
api-version: 1.21
author: Wolfsketch
description: Clan system with land claiming, power, vaults, and raid management.

commands:
  clan:
    description: Clan management and raid control command
    usage: /clan <create|join|leave|info|vault|invite|raid>
    aliases: []
  claim:
    description: Claim land for your clan
    usage: /claim
    aliases: []

permissions:
  clanspvp.create:
    description: Allows creation of a clan
    default: true

  clanspvp.claim:
    description: Allows claiming land for your clan
    default: true

  clanspvp.vault:
    description: Allows access to the clan vault
    default: true

  clanspvp.raid.start:
    description: Allows starting a raid (clan leader or authorized roles only)
    default: false

  clanspvp.raid.stop:
    description: Allows stopping an active raid
    default: false

  clanspvp.raid.check:
    description: Allows checking the current raid location
    default: true

  clanspvp.admin:
    description: Grants full access to ClansPvP admin commands
    default: op
