name: ClansPvP
main: me.jason.clanspvp.ClansPvP
version: 1.1.0
api-version: 1.21
author: Wolfsketch
description: >
  Complete clan system featuring land claiming, power, vaults, raids, warps,
  ally-warps, GitHub issue reporter, and admin tools.

# ─── Load order ─────────────────────────────────────────
depend: [Vault]
softdepend:
  - LuckPerms
  - Essentials

# ─── Commands ───────────────────────────────────────────
commands:
  clan:
    description: Manage your clan (create, invite, claim, warp, raid, etc.)
    usage: /clan <subcommand>
    aliases: []
    tab-completer: me.jason.clanspvp.commands.ClanTabCompleter

  clanmap:
    description: Show a local map of nearby claimed chunks
    usage: /clanmap
    aliases: []

# ─── Permissions ────────────────────────────────────────
permissions:
  # General
  clanspvp.create:
    description: Allows creating a clan
    default: true
  clanspvp.claim:
    description: Allows claiming chunks
    default: true
  clanspvp.unclaim:
    description: Allows unclaiming chunks
    default: true
  clanspvp.vault:
    description: Allows opening the clan vault
    default: true
  clanspvp.vault.bonus:
    description: Grants 10 extra vault slots
    default: false

  # Warp permissions
  clanspvp.warp.set:
    description: Allows setting a clan warp (/clan setwarp)
    default: false
  clanspvp.warp.use:
    description: Allows teleporting to clan warps (/clan warp)
    default: true

  # Ally-warp permissions
  clanspvp.warp.ally.set:
    description: Allows setting an ally warp (/clan ally setwarp)
    default: false
  clanspvp.warp.ally.use:
    description: Allows using ally warps (/clan ally warp)
    default: true

  # Issue reporter
  clanspvp.issue:
    description: Allows creating GitHub issues via /clan issue
    default: true

  # Raid
  clanspvp.raid.start:
    description: Allows starting a raid
    default: false
  clanspvp.raid.stop:
    description: Allows stopping a raid
    default: false
  clanspvp.raid.check:
    description: Allows checking raid location
    default: true

  # Clan management
  clanspvp.invite:
    description: Allows inviting players
    default: true
  clanspvp.promote:
    description: Allows promoting members
    default: false
  clanspvp.demote:
    description: Allows demoting members
    default: false
  clanspvp.leave:
    description: Allows leaving a clan
    default: true
  clanspvp.join:
    description: Allows requesting to join a clan
    default: true

  # Ally-trust toggle
  clanspvp.ally.trust:
    description: Allows toggling build-trust with an allied clan
    default: op

  # Administration
  clanspvp.reload:
    description: Allows /clan reload
    default: op
  clanspvp.admin:
    description: Grants all ClansPvP administrative features
    default: op
